version: 2

jobs:
  test_7.1:
    working_directory: ~/env-providers
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit

  test_7.1_lowest:
    working_directory: ~/env-providers
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer update --prefer-lowest --prefer-dist --no-progress --no-suggest
      - run: ./vendor/bin/phpunit

  test_7.2:
    working_directory: ~/env-providers
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit

  test_7.2_lowest:
    working_directory: ~/env-providers
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer update --prefer-lowest --prefer-dist --no-progress --no-suggest
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test_7.1
      - test_7.1_lowest
      - test_7.2
      - test_7.2_lowest
